[config]
rpc = "https://fullnode.testnet.sui.io:443"

[packages]
Sui = { git = "https://github.com/alexanderludwig/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "main" }
aeon-custody = {local = "../../../move/custody"}

